import { GithubEvent } from '../lib/models/pageProps';

export const mockProfile = {
  id: 12345678,
  node_id: 'MDQ6VXNlcjEyMzQ1Njc4',
  avatar_url: 'https://avatars.githubusercontent.com/u/12345678',
  gravatar_id: '',
  url: 'https://api.github.com/users/janedoe',
  html_url: 'https://github.com/janedoe',
  followers_url: 'https://api.github.com/users/janedoe/followers',
  following_url: 'https://api.github.com/users/janedoe/following{/other_user}',
  gists_url: 'https://api.github.com/users/janedoe/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/janedoe/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/janedoe/subscriptions',
  organizations_url: 'https://api.github.com/users/janedoe/orgs',
  repos_url: 'https://api.github.com/users/janedoe/repos',
  events_url: 'https://api.github.com/users/janedoe/events{/privacy}',
  received_events_url: 'https://api.github.com/users/janedoe/received_events',
  type: 'User',
  site_admin: false,
  name: 'Jane Doe',
  company: null,
  blog: '',
  location: 'Kansas City, MO',
  email: null,
  hireable: null,
  bio: 'Software Developer',
  twitter_username: null,
  public_repos: 42,
  public_gists: 5,
  followers: 100,
  following: 50,
  created_at: '2015-01-01T00:00:00Z',
  updated_at: '2024-01-15T12:00:00Z',
  login: 'janedoe',
  two_factor_authentication: false,
};

export const mockEvents: GithubEvent[] = [
  {
    id: '1',
    type: 'PushEvent',
    repo: { name: 'janedoe/my-project' },
    payload: { commits: [{ message: 'Fix login bug' }, { message: 'Update README' }] },
    created_at: '2024-01-15T10:30:00Z',
  },
  {
    id: '2',
    type: 'PullRequestEvent',
    repo: { name: 'janedoe/my-project' },
    payload: { commits: [] },
    created_at: '2024-01-14T08:00:00Z',
  },
  {
    id: '3',
    type: 'PushEvent',
    repo: { name: 'janedoe/other-repo' },
    payload: { commits: [{ message: 'Initial commit' }] },
    created_at: '2024-01-13T15:45:00Z',
  },
];
