import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Session } from "next-auth";
import { Header } from "@keyhole/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Keyhole Next App",
  description: "Generated by create next app, customized by Keyhole Software",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: Session | null;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header session={session}/>
        {children}
      </body>
    </html>
  );
}
