import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@keyhole/components/organisms/header";
import { getServerSession } from "@keyhole/services/AuthService";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Keyhole Next App",
  description: "Generated by create next app, customized by Keyhole Software",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header session={session}/>
        {children}
      </body>
    </html>
  );
}
